import type { Values } from "./types";

export const INITIAL_VALUES: Values = {
  Username: "",
  Title: "",
  Year: "",
  Runtime: 1,
  Genre: [],
  Director: "",
};

export const GENRES = [
  { id: "action", name: "Action" },
  { id: "adventure", name: "Adventure" },
  { id: "animation", name: "Animation" },
  { id: "biography", name: "Biography" },
  { id: "comedy", name: "Comedy" },
  { id: "crime", name: "Crime" },
  { id: "documentary", name: "Documentary" },
  { id: "drama", name: "Drama" },
  { id: "family", name: "Family" },
  { id: "fantasy", name: "Fantasy" },
  { id: "film-noir", name: "Film-Noir" },
  { id: "history", name: "History" },
  { id: "horror", name: "Horror" },
  { id: "music", name: "Music" },
  { id: "musical", name: "Musical" },
  { id: "mystery", name: "Mystery" },
  { id: "romance", name: "Romance" },
  { id: "sci-fi", name: "Sci-Fi" },
  { id: "sport", name: "Sport" },
  { id: "thriller", name: "Thriller" },
  { id: "war", name: "War" },
  { id: "western", name: "Western" },
  { id: "short", name: "Short" },
  { id: "reality-tv", name: "Reality-TV" },
  { id: "talk-show", name: "Talk-Show" },
  { id: "game-show", name: "Game-Show" },
  { id: "adult", name: "Adult" },
  { id: "superhero", name: "Superhero" },
  { id: "disaster", name: "Disaster" },
  { id: "teen", name: "Teen" },
  { id: "cyberpunk", name: "Cyberpunk" },
  { id: "survival", name: "Survival" },
  { id: "martial-arts", name: "Martial Arts" },
];

export const INITIAL_ADD_DATA = {
  Country: "N/A",
  Production: "N/A",
  Metascore: "N/A",
  Rated: "N/A",
  Plot: "N/A",
  Actors: "N/A",
  Writer: "N/A",
  Awards: "N/A",
  Rating: [
    { Source: "Internet Movie Database", Value: "N/A" },
    { Source: "Rotten Tomatoes", Value: "N/A" },
    { Source: "Metacritic", Value: "N/A" },
  ],
  imdbRating: "N/A",
  imdbVotes: "N/A",
  BoxOffice: "N/A",
};
